### ISSUE TITLE
Evaluating functions at 0 always returns 0

### ISSUE THREAD

**Issue by Jilhg** [JuliaApproximation/ApproxFunFourier.jl#125]
I noticed that for some periodic segments evaluating a function at 0 always produces 0. For instance

```
xmin,xmax=-2,3
S=CosSpace(xmin..xmax)

g=Fun(S,[1.0])
xs=LinRange(xmin,xmax,101)
plot(xs,g)
```
has the following output
![image](https://github.com/user-attachments/assets/885c912c-13f1-4706-96be-6931ea5f4b03)

This is caused because 0 is apparently not contained in the periodic segment:
```
0∈domain(S) # False
```
which is checked before function evaluation (ApproxFunFourier.jl, l.267).

The following code in Domains.jl is responsible for this behavior:

```
function indomain(x, d::PeriodicDomain{T}) where T
    y=tocanonical(d,x)
    if !isapprox(fromcanonical(d,y),x)
        return false
    end
    ...
end
```

If `x=0` then `fromcanonical(d,y)= 1.1102230246251565e-16` and thus `isapprox` returns false. I guess one way of solving this issue would be to specify an `atol=...` in `isapprox`.

**Comment by jishnub** [comment]
Would you mind making a PR?

**Comment by Jilhg** [comment]
I can do, what value of `atol` should I choose? `1e-15`? Feels a bit hacky, I guess there will always be some `x` that are not covered. I could also overload `indomain` specifically for `PeriodicSegments`?
